spring:
  security:
    oauth2:
      client:
        registration:
          salesforce:
            token-name: access_token
            client-id: replace-me
            client-secret: replace-me
            scope: api, refresh_token, id, profile
            redirect-uri: http://localhost:8080/login/oauth2/code/salesforce
            authorization-grant-type: authorization_code
        provider:
          salesforce:
            token-uri: https://login.salesforce.com/services/oauth2/token
            authorization-uri: https://login.salesforce.com/services/oauth2/authorize
            user-info-uri: https://login.salesforce.com/services/oauth2/userinfo
            userNameAttribute: sub
